name: "ShellCheck"

on:
  push:
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 20 * * 4'

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: shellcheck *.sh
